server:
  port: 1200
#  servlet:
#    context-path: "/banking"#context patha always start with "/".
#    we declare this because we know the application by local host during microservices.

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306"
    username: "root"
    password: "root"

  sql:
    init:
      mode: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


