server:
  port: 1200
  servlet:
    context-path: "/sbi"#context patha always start with "/".
#    we declare this because we know the application by local host during microservices.

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sbi"
    username: "root"
    password: "root"


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


